-- 관계 연산자
-- NOT, AND, OR, BETWEEN, IN

-- 조회수가 0, 1, 2인 게시글을 조회하시오
SELECT * FROM NOTICE WHERE HIT = 0 OR HIT = 1 OR HIT = 2;

SELECT * FROM NOTICE WHERE HIT IN(0,1,2) ORDER BY ID ASC;

SELECT * FROM NOTICE WHERE HIT >= 0 AND HIT <= 3 ORDER BY ID ASC;

SELECT * FROM NOTICE WHERE HIT BETWEEN 0 AND 2 ORDER BY ID ASC;

-- 조회수가 0, 2, 7인 게시글을 조회하시오
SELECT * FROM NOTICE WHERE HIT = 0 OR HIT = 2 OR HIT = 7;
SELECT * FROM NOTICE WHERE HIT IN(0,2,7);
SELECT * FROM NOTICE WHERE HIT NOT IN(0,2,7);