
-- View(뷰)의 의미와 생성방법
 -- 물리적인 데이터구조( Table )와 개념적인 데이터구조( View )의 차이
 
-- View 상태로 보여주면서 게시글 조인하기
-- View로 사용될 쿼리
 SELECT NTC.ID, NTC.TITLE, NTC.WRITER_ID, MEM.NAME, COUNT(CMT.ID) CNT
   FROM MEMBER MEM
RIGHT OUTER JOIN NOTICE NTC ON MEM.ID = NTC.WRITER_ID
LEFT OUTER JOIN "COMMENT" CMT ON NTC.ID = CMT.NOTICE_ID
GROUP BY NTC.ID, NTC.TITLE, NTC.WRITER_ID, MEM.NAME;

-- View 생성하기
-- 위의 쿼리 문장을 VIEW로 정의해서 사용하기
CREATE VIEW NOTICEVIEW AS
SELECT NTC.ID, NTC.TITLE, NTC.WRITER_ID, MEM.NAME, COUNT(CMT.ID) CNT
   FROM MEMBER MEM
RIGHT OUTER JOIN NOTICE NTC ON MEM.ID = NTC.WRITER_ID
LEFT OUTER JOIN "COMMENT" CMT ON NTC.ID = CMT.NOTICE_ID
GROUP BY NTC.ID, NTC.TITLE, NTC.WRITER_ID, MEM.NAME;

-- VIEW를 이용해 쿼리 만들기 ( 마치 테이블처럼 하나의 단위로 사용할수 있음 )
-- 쿼리를 하나의 테이블 형식처럼 쿼리를 작성할수 있다.
SELECT *  FROM NOTICEVIEW;